### ISSUE TITLE
cr_tamerinventory full

### ISSUE THREAD

**Issue by ghost** [NoImageAvailable/CombatRealism#18] opened 2016-05-06 20:07 UTC
Reference screenshots. Tl;dr my settlement's animal trainer tends to have a nasty habit of filling up her inventory and trying to pick up more than she can carry.

Using what I believe is the latest download seeing as how I grabbed it maybe ten minutes ago.

![ss 2016-05-06 at 04 02 37](https://cloud.githubusercontent.com/assets/8041697/15084856/4a40dd84-13a4-11e6-8e27-905b9febf60c.png)
![ss 2016-05-06 at 04 02 49](https://cloud.githubusercontent.com/assets/8041697/15084855/4a238acc-13a4-11e6-97ca-e0d05aa9d24b.png)

**Comment by NoImageAvailable** [comment] 2016-05-08 12:23
Warning message is missing a translation string, should be fixed in next release. Otherwise this is working as intended: when full on inventory space tamers show a warning message to signal the player they can't do their job because of their inventory being full.

**Closed as completed by NoImageAvailable** 2016-05-08 12:23 UTC
